[package]
name = "uniswap-lens"
version = "0.0.1"
edition = "2021"
authors = ["Shuhui Luo <twitter.com/aureliano_law>"]
description = "Contains ephemeral lens contracts that can be called without deployment and their Rust interfaces."
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/shuhuiluo/uniswap-lens-rs"
keywords = ["alloy", "ethereum", "solidity", "rust", "uniswap"]
include = ["src/**/*.rs"]

[dependencies]
alloy = { version = "0.2.0", features = ["contract", "provider-http"] }
anyhow = "1"
once_cell = "1.19"

[dev-dependencies]
dotenv = "0.15.0"
futures = "0.3"
tokio = { version = "1.37", features = ["full"] }
